name: IOT IJK ANDROID DEBUG CI

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [ master ]

env:
  IOT_SONATYPE_USERNAME: ${{ secrets.IOT_SONATYPE_USERNAME }}
  IOT_SONATYPE_PASSWORD: ${{ secrets.IOT_SONATYPE_PASSWORD }}
  GPG_DECRYPT_PASSPHRASE: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11    
      - name: Download r14b NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r14b-darwin-x86_64.zip
          unzip android-ndk-r14b-darwin-x86_64.zip
      - name: Update SDK Version
        run: bash .github/script/updateVersionForSnapshot.sh
      - name: Build with Gradle
        run: |
          ls -l /Users/runner/work/iot-ijkplayer/iot-ijkplayer/android-ndk-r14b
          export ANDROID_NDK=/Users/runner/work/iot-ijkplayer/iot-ijkplayer/android-ndk-r14b
          export ANDROID_NDK_ROOT=/Users/runner/work/iot-ijkplayer/iot-ijkplayer/android-ndk-r14b

          sh .github/script/build_armv7a.sh
          cd android/ijkplayer
          ./gradlew :ijkplayer-armv7a:assemble
          ./gradlew :ijkplayer-arm64:assemble
          ./gradlew :ijkplayer-java:assemble

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload AAR files
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: android/ijkplayer/ijkplayer-armv7a/build/outputs/aar/ijkplayer-armv7a-release.aar
          asset_name: ijkplayer-armv7a-release.aar
          asset_content_type: application/aar
      - name: Upload AAR files for arm64
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: android/ijkplayer/ijkplayer-arm64/build/outputs/aar/ijkplayer-arm64-release.aar
          asset_name: ijkplayer-arm64-release.aar
          asset_content_type: application/aar
      - name: Upload AAR files for java
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: android/ijkplayer/ijkplayer-java/build/outputs/aar/ijkplayer-java-release.aar
          asset_name: ijkplayer-java-release.aar
          asset_content_type: application/aar
          
      # - name: Publish aar to Maven
      #   run: |
      #     cd android/ijkplayer
      #     ./gradlew :ijkplayer-armv7a:publish
      #     ./gradlew :ijkplayer-arm64:publish
      #     ./gradlew :ijkplayer-java:publish
